export const INVENTORYS_LIST_REQUEST = "INVENTORYS_LIST_REQUEST";
export const INVENTORYS_LIST_SUCCESS = "INVENTORYS_LIST_SUCCESS";
export const INVENTORYS_LIST_FAIL = "INVENTORYS_LIST_FAIL";

export const INVENTORYS_CREATE_REQUEST = "INVENTORYS_CREATE_REQUEST";
export const INVENTORYS_CREATE_SUCCESS = "INVENTORYS_CREATE_SUCCESS";
export const INVENTORYS_CREATE_FAIL = "INVENTORYS_CREATE_FAIL";


export const INVENTORYS_UPDATE_REQUEST = "INVENTORYS_UPDATE_REQUEST";
export const INVENTORYS_UPDATE_SUCCESS = "INVENTORYS_UPDATE_SUCCESS";
export const INVENTORYS_UPDATE_FAIL = "INVENTORYS_UPDATE_FAIL";
